#include "ParticleEmitterInstances.h"

FParticleEmitterBuildInfo::FParticleEmitterBuildInfo()
    : RequiredModule(NULL)
    , SpawnModule(NULL)
    , SpawnPerUnitModule(NULL)
    , MaxSize(1.0f, 1.0f)
    , SizeScaleBySpeed(FVector2D::ZeroVector)
    , MaxSizeScaleBySpeed(1.0f, 1.0f)
    , bEnableCollision(false)
    /*, CollisionResponse(EParticleCollisionResponse::Bounce)
    , CollisionMode(EParticleCollisionMode::SceneDepth)
    , CollisionRadiusScale(1.0f)
    , CollisionRadiusBias(0.0f)
    , CollisionRandomSpread(0.0f)
    , CollisionRandomDistribution(1.0f)
    , Friction(0.0f)*/
    , PointAttractorPosition(FVector::ZeroVector)
    , PointAttractorRadius(0.0f)
    , GlobalVectorFieldScale(0.0f)
    , GlobalVectorFieldTightness(-1)
    , LocalVectorField(NULL)
    , LocalVectorFieldTransform(FTransform::Identity)
    , LocalVectorFieldIntensity(0.0f)
    , LocalVectorFieldTightness(0.0f)
    , LocalVectorFieldMinInitialRotation(FVector::ZeroVector)
    , LocalVectorFieldMaxInitialRotation(FVector::ZeroVector)
    , LocalVectorFieldRotationRate(FVector::ZeroVector)
    , ConstantAcceleration(0.0f)
    , MaxLifetime(1.0f)
    , MaxRotationRate(1.0f)
    , EstimatedMaxActiveParticleCount(0)
    //, ScreenAlignment(PSA_Square)
    , PivotOffset(-0.5, -0.5)
    , bLocalVectorFieldIgnoreComponentTransform(false)
    , bLocalVectorFieldTileX(false)
    , bLocalVectorFieldTileY(false)
    , bLocalVectorFieldTileZ(false)
    , bLocalVectorFieldUseFixDT(false)
    , bUseVelocityForMotionBlur(0)
    , bRemoveHMDRoll(0)
    , MinFacingCameraBlendDistance(0.0f)
    , MaxFacingCameraBlendDistance(0.0f)
{
    // 현재는 LookUp Table을 사용하지 않으므로 Initialize 안해두 됨
}
